title: FreeGamesOnline.ee
author: FreeGamesOnline.ee, contributors
description: The official FreeGamesOnline.ee blog.
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  style: compressed
include:
  - assets